### ISSUE TITLE
Not working if machine has empty api port

### ISSUE THREAD

**Issue by ninja-** [rfrail3/grafana-dashboards#44]
This is my node uname on rancher with custom hostname
```
node_uname_info{domainname="(none)",endpoint="https",instance="c1",job="node-exporter",machine="x86_64",namespace="monitoring",nodename="c1",pod="node-exporter-l922f",release="5.3.0-19-generic",service="node-exporter",sysname="Linux",version="#20~18.04.2-Ubuntu SMP Tue Oct 22 18:09:07 UTC 2019"}
--
```

Your dashboard is expecting all nodenames to be host:port which means I can't view any data...

**Comment by ninja-** [comment]
I patched the file with `sed s/:\$port//g` and removed the regex in variables and I got it to work

**Comment by stemid** [comment]
@ninja- could you elaborate on how you did that? I tried going into the dashboard settings, JSON Model, copying the JSON into an editor, replacing ':$port' with nothing in the whole file, pasting it back and then it just stopped working.

I have a query like this in one of the panels 

    sum by (instance)(irate(node_cpu_seconds_total{mode="system",instance=~"$node",job=~"$job"}[5m])) * 100

And I have a drop down with nodes and jobs at the top. So if I paste that query into Explore and replace $node with a real node, $job with node_exporter, it works!

But it won't work in the actual dashboard with the variables.

I've also removed the port variable from the settings so that drop down doesn't appear anymore, but that was after I tried the dashboard after editing it so that didn't help.

**Comment by stemid** [comment]
I managed to resolve this myself. Here's for anyone else hitting this issue through google.
I had removed the port with prometheus relabel so this dashboard didn't work. Steps to make it work;
1. Remove the ':$port' suffix from the JSON and save the JSON. Just like ninja- above says using sed for example.
2. Go into the grafana web ui, Settings for the dashboard, Variables. Here you can start by removing the port variable since it's not needed. But most importantly you need to update the node variable and remove its Regex setting. Now the dashboard started working for me.

**Comment by ninja-** [comment]
your points 1 and 2 are exactly what I did, I am glad you got it working
